const userTypes = {
  EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
  GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  SIGNOUT_USER_START: 'SIGNOUT_USER_START',
  SIGNOUT_USER_SUCCESS: 'SIGNOUT_USER_SUCCESS',
  SIGN_UP_START: 'SIGN_UP_START',
  PASSWARD_RESET_START: 'PASSWARD_RESET_START',
  PASSWARD_RESET_SUCCESS: 'PASSWARD_RESET_SUCCESS',
  USER_ERRORS: 'USER_ERRORS',
  RESET_USER_STATE: 'RESET_USER_STATE',
};

export default userTypes;