const userTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_ERRORS: 'SIGNUP_ERRORS',
  PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',
  PASSWORD_RESET_ERRORS: 'PASSWORD_RESET_ERRORS',
  RESET_AUTH_FORMS: 'RESET_AUTH_FORMS',
};

export default userTypes;